### PR TITLE
Fixing output if ./hack/update-codegen.sh doesn't update

### LINKED ISSUE #1238: ./hack/update-codegen.sh doesn't do anything
After adding my github handle to both `peribolos/knative.yaml` and `peribolos/knative-sandbox.yaml`, when I run `./hack/update-codegen.sh`, it says that it has added me to both `peribolos/knative-OWNERS_ALIASES` and `peribolos/knative-sandbox-OWNERS_ALIASES`, but nothing changes.

Steps to reproduce:
1. Add a new github handle to `members` in `peribolos/knative.yaml` and `peribolos/knative-sandbox.yaml`
2. Run `./hack/update-codegen.sh`
 - You should see the following output:
```
➜ ./hack/update-codegen.sh
2022/12/16 09:20:10 Wrote peribolos/knative-OWNERS_ALIASES
2022/12/16 09:20:10 Wrote peribolos/knative-sandbox-OWNERS_ALIASES
```
 - Then, running `git status` repots that no files were changed. 
 - If you open the files and search for the new handle, you can confirm it hasn't been added.

### PR DESCRIPTION
**Pull request by Bisht13**
# Changes

- :broom: The output of ./hack/update-codegen.sh prints ```No changes to 'filename'``` if it doesn't update peribolos.

/kind cleanup

Fixes #1238

### CODE REVIEW

**Comment by psschwei** [comment]
Thanks for the PR @Bisht13 !!

You'll need to sign the CLA before we can merge this (there's instructions above on how to do so).

/ok-to-test
/hold
to prevent merge queue issues until CLA is signed

**Comment by Bisht13** [comment]
> Thanks for the PR @Bisht13 !!
> 
> You'll need to sign the CLA before we can merge this (there's instructions above on how to do so).
> 
> /ok-to-test /hold to prevent merge queue issues until CLA is signed

Done ✨

File: mechanics/tools/gen-aliases/main.go [hunk 1]
```diff
@@ -63,6 +63,11 @@ func main() {
 
 `, infile)
 	output = append([]byte(preamble), output...)
+	prevOut, err := ioutil.ReadFile(outfile)
+	if err == nil && string(prevOut) == string(output) {
+		log.Print("No changes to ", outfile)
+		return
+	}
```
Comment (kvmware) [inline mechanics/tools/gen-aliases/main.go:70]: Should not write to `outfile` if the content is the same. ie: put `else` for the write.

Comment (kvmware) [reply mechanics/tools/gen-aliases/main.go:70]: also, to make it clear I would put "No changes needed for " instead of the "No changes to " which might be ambiguous

Comment (kvmware) [reply mechanics/tools/gen-aliases/main.go:70]: you can remove the `return` when you use `else

Comment (Bisht13) [reply mechanics/tools/gen-aliases/main.go:72]: Made requested changes ✨

**Comment by psschwei** [comment]
cla signed 
/hold cancel

**Comment by kvmware** [comment]
Thanks for the PR! :pray: 
/lgtm
@psschwei if it looks good to you please give it the /approve

**Review by psschwei — COMMENTED** [review]
Gave it a manual test and works as expected.
Thanks @Bisht13 !!

/approve

File: mechanics/tools/gen-aliases/main.go [hunk 2]
```diff
@@ -63,8 +63,13 @@ func main() {
 
 `, infile)
 	output = append([]byte(preamble), output...)
-	ioutil.WriteFile(outfile, output, 0644)
-	log.Print("Wrote ", outfile)
+	prevOut, err := ioutil.ReadFile(outfile)
```
Comment (dprotaso) [inline mechanics/tools/gen-aliases/main.go:66]: As a follow up can you drop the use of `ioutil.ReadFile` it's deprecated

https://pkg.go.dev/io/ioutil#ReadFile

I guess we don't lint the code in this repo

Comment (kvmware) [reply mechanics/tools/gen-aliases/main.go:66]: Opened an issue for the linting here https://github.com/knative/community/issues/1276.

@Bisht13 Do you mind updating the `ReadFile` request above or at least open an issue if you don't have the time. That was my bad for not catching that sorry.

Comment (Bisht13) [reply mechanics/tools/gen-aliases/main.go:66]: I'll fix that

Comment (Bisht13) [reply mechanics/tools/gen-aliases/main.go:66]: @dprotaso made an issue #1278 and opened a PR #1279 ✨
